### ISSUE TITLE
The 10th nested res comment isn't styled with a proper bg color

### ISSUE THREAD

**Issue by Fluxflashor** [redditwow/stylesheet#1]
http://i.imgur.com/Sk6ScWA.png

Specifically on this comment if you go back to the main thread
https://www.reddit.com/r/wow/comments/523k9c/i_wouldnt_really_say_you_resolved_my_problems/d7hluwa

Also style overall is pretty neat, great job on it!

**Comment by Vusys** [comment]
Fixed in 76ad79fcba91e85015fa68aebe022b23fdab9d25. Thanks.
