### ISSUE TITLE
RES markdown bar isn't themed

### ISSUE THREAD

**Issue by Fluxflashor** [redditwow/stylesheet#2]
http://i.imgur.com/7MIXWQF.png

Pretty minor, not sure if you guys even want to go for it, but it would be a nice addition to the page. Currently stands out quite a bit on the page.

**Comment by Vusys** [comment]
Yeah. Annoyingly the icons that RES use are all bitmaps, so I can't just override the colour on them. Would have to replace them with new assets.

**Comment by Vusys** [comment]
The RES markdown toolbar has been restyled now. 

![](https://dl.dropboxusercontent.com/u/62398/Screenshots/2016-11-26_142017.png)

0c14db28d2d2594805ddacc1ffa44da000134f20
